# Generated by Django 4.2.25 on 2025-10-06 05:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("content_tools", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generatedcontent",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
