# Generated by Django 5.2.5 on 2025-09-25 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0002_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="blog_image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
