# Generated by Django 5.2.5 on 2025-09-27 07:46

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0003_blog_blog_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="blog_image",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="image"
            ),
        ),
    ]
